---
- hosts: windows_vm
  tasks: 
    - name: Running Windows Update
      win_updates:
        category_names: ['SecurityUpdates','CriticalUpdates','UpdateRollups', 'Updates', 'DefinitionUpdates']
        reboot: yes
      register: result

    - debug: var=result

    - name: Actualizo Plesk
      win_shell: 'plesk installer --select-release-latest --upgrade-installed-components  '
    
    - name: Actualizo git
      win_shell: 'plesk bin extension --upgrade git'
   
